name:                HaddockIssue1472
version:             0.1.0.0
github:              "githubuser/HaddockIssue1472"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/HaddockIssue1472#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- random
- mtl
- directory
- array

library:
  source-dirs: src

executables:
  HaddockIssue1472-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaddockIssue1472

tests:
  HaddockIssue1472-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaddockIssue1472
    - tasty
    - tasty-quickcheck
    - tasty-hunit
